### ISSUE TITLE
bug: sending registration email to already existing user

### ISSUE THREAD

**Issue by himanshu010** [himanshu010/onlineIDE#6]
bug: sending registration email to already existing user

Explanation:
If an already registered user signs up. The platform shows the error of "user already exists" but the backend sends registration mail to that user.

Helpful files:
https://github.com/himanshu010/onlineIDE/blob/master/src/routes/otp/otp.js
https://github.com/himanshu010/onlineIDE/blob/master/src/routes/user/signup/register.js
https://github.com/himanshu010/onlineIDE/blob/master/src/routes/user/signup/signup.js
https://github.com/himanshu010/onlineIDE/blob/master/src/routes/user/signup/emailVerification.js

**Comment by snitin315** [comment]
Cliaming the bounty.

**Comment by ambuj0106** [comment]
Let me try will do in 999rs
